import "./globals.css";
import { Inter } from "next/font/google";
import { unstable_getServerSession } from "next-auth/next";
import { Component } from "react";
import Header from "@/components/header/defaultHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  dashboard,
  login,
  children,
}: {
  dashboard: React.ReactNode;
  login: React.ReactNode;
  children: React.ReactNode;
}) {
  const session = await unstable_getServerSession();
  console.log("session", session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header logo={"/next.svg"} />
        {session ? dashboard : login}
        {children}
      </body>
    </html>
  );
}
